create table t5 (id number(10),ville varchar(100),ville2 varchar(100), pays varchar(100), pays2 varchar(100));
insert into t5 values(1,'paris','Otaki','FRANCE','FRANCE');
insert into t5 values(2,'lyon','Otaki','FRANCE','FRANC');
insert into t5 values(3,'paris','Otaki','FRANCE','');
insert into t5 values(4,'Three Legged Cross','Otaki','FRANCE','FRANCE');
insert into t5 values(5,'Nottingham','Otaki','FRANCE','Royaume-Uni');
insert into t5 values(6,'Latina','Otaki','FRANCE','Espagne');
insert into t5 values(7,'Teo','Otaki','FRANCE','ESPAGNE');
insert into t5 values(8,'bordeau','Otaki','FRANCE','Italie');
insert into t5 values(9,'VALENCIA','Otaki','FRANCE','SPAIN');
insert into t5 values(10,'VALENCIA','Otaki','FRANCE','SPAIN');
insert into t5 values(11,'VALENCE','Otaki','FRANCE','SPAIN');
insert into t5 values(12,'Orense','Otaki','FRANCE','ESPAGNE');
insert into t5 values(13,'lyon','Otaki','FRANCE','FRANC');
