DROP TABLE phone_num;
CREATE TABLE phone_num(pays VARCHAR2(50),numero NUMBER(10));
INSERT INTO phone_num VALUES ('COUNTRYEUR001','33');
INSERT INTO phone_num VALUES ('COUNTRYEUR002','49');
INSERT INTO phone_num VALUES ('COUNTRYEUR003','32');
INSERT INTO phone_num VALUES ('COUNTRYEUR004','45');
INSERT INTO phone_num VALUES ('COUNTRYEUR005','30');
INSERT INTO phone_num VALUES ('COUNTRYEUR006','39');
INSERT INTO phone_num VALUES ('COUNTRYEUR007','34');
