DROP TABLE VENTES_DW2B ;
PROMPT =====================================================================
PROMPT >> Création de la Table : VENTES_DW2B
PROMPT =====================================================================
CREATE TABLE VENTES_DW2B (
    NUMVENTE INTEGER,
    NUMART INTEGER,
    IDTEMPS INTEGER,
    NUMCLI INTEGER,
    MONTANTVENTE NUMBER(20,4),
    NUMMAG VARCHAR(4),
    CONSTRAINT PK_VENTES_DW2B PRIMARY KEY(NUMVENTE)
);

INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (1, 30, 5, 2, 28.99, 'FR02');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (2, 28, 4, 3, 28.99, 'FR04');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (3, 26, 6, 1 ,22.00, 'FR06');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (4, 24, 7, 8, 21.00, 'BE02');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (5, 22, 5, 9, 24.90, 'TN01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (6, 11, 11, 11, 122.00, 'TN01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (7, 18, 12, 14 ,44.00, 'IT01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (8, 16, 12, 2, 49.00, 'TN01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (9, 14, 2, 4, 7.80, 'FR03');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (10, 12, 6, 5, 15.55, 'FR02');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (11, 10, 8 ,12, 30.70, 'BE03');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (12, 8, 9, 11, 3.00,'TN01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (13, 6, 1, 4, 2.00, 'FR02');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (14, 4, 10, 14 ,7.40, 'IT01');
INSERT INTO VENTES_DW2B (NUMVENTE, NUMART, IDTEMPS, NUMCLI, MONTANTVENTE, NUMMAG) VALUES (15, 2, 3, 3 , 27.00, 'FR05');
COMMIT;