@annexe2.sql
DROP TABLE VENTES_DW2B_FR;
CREATE TABLE VENTES_DW2B_FR AS SELECT * FROM VENTES_DW2B;
SELECT count(*) FROM VENTES_DW2B_FR;
SELECT count(*) FROM VENTES_DW2B_FR WHERE NUMMAG LIKE 'FR%';
DELETE FROM VENTES_DW2B_FR WHERE NUMMAG NOT LIKE 'FR%';
SELECT count(*) FROM VENTES_DW2B_FR;

-- B.2.1
select count(*) as nb, SUBSTR(nummag, 1, 2) as pays from VENTES_DW2B group by SUBSTR(nummag, 1, 2);
