Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','DRUMSITE');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','FLYING FISH COVE');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','SETTLEMENT');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','SOUTH POINT');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','THE SETTLEMENT');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('CX','WATERFALL');
