Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','INE');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','JABOORU');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','JABOR');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','JABORU');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','JABWOR');
Insert into DATA_DICTIONARY_CITY (COUNTRY_ALPHA2, CITY_NAME) values ('MH','MAJURO');
